-- DROP TABLE IF EXISTS study_plans;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;

CREATE TABLE groups
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE students
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR NOT NULL,
    last_name  VARCHAR NOT NULL,
    age        INT CHECK (age >= 1),
    group_id   INT     REFERENCES groups (id) ON DELETE SET NULL,
    -- marks
    math        INT CHECK (math BETWEEN 1 and 5),
    geometry    INT CHECK (geometry BETWEEN 1 and 5),
    informatics INT CHECK (informatics BETWEEN 1 and 5),
    physics     INT CHECK (physics BETWEEN 1 and 5),
    russian     INT CHECK (russian BETWEEN 1 and 5),
    literature  INT CHECK (literature BETWEEN 1 and 5)
);

CREATE TABLE subjects
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR
);

-- CREATE TABLE study_plans
-- (
--     group_id INT REFERENCES groups (id) ON DELETE NO ACTION,
--     subject  VARCHAR NOT NULL,
--     hours    INT     NOT NULL CHECK (hours >= 0)
-- );
